### ISSUE TITLE
Replace all instances of [svg series...] with native svg

### ISSUE THREAD

**Issue by dsifford** [aliemteam/ALiEM#47]
## Todo

- [x] 2017 Consensus Conference on Resident Wellness (CCRW)
- [x] AIR Pro Series: Critical Care, Part 1 (2016)
- [x] AIR Series and AIR-Pro Series are moving to ALiEMU!
- [x] AIR Series: Cardiology - CHF, PVD, and Others (part 2)
- [x] AIR Series: Cardiology Module, Part 1 (2015)
- [x] AIR Series: Cutaneous Module
- [x] AIR Series: Endocrinology Module 2014
- [x] AIR Series: Environmental Module
- [x] AIR Series: Environmental Module 2
- [x] AIR Series: GU/Renal Module 2015
- [x] AIR Series: HEENT Module 2014
- [x] AIR Series: Infectious Disease Module (2016)
- [x] AIR Series: Infectious Disease, Hematology, Oncology 2014
- [x] AIR Series: Neurology Module 1 - Bleeds and Strokes
- [x] AIR Series: Neurology Module 2 - Headaches, Seizures, and Other
- [x] AIR Series: Ob/Gyn Module 2015
- [x] AIR Series: Orthopedics Lower Extremity Module (2016)
- [x] AIR Series: Orthopedics Upper Extremity Module (2016)
- [x] AIR Series: Peripheral Vascular Disease Module 2014
- [x] AIR Series: Procedures Module (2016)
- [x] AIR Series: Psychiatry Module 2014
- [x] AIR Series: Respiratory Module (2016)
- [x] AIR Series: Respiratory Part 1 (2015)
- [x] AIR Series: Respiratory Part 2 (2015)
- [x] AIR Series: Toxicology Module 2015
- [x] AIR-Pro Series: Cardiovascular (2015)
- [x] AIR-Pro Series: Critical Care (part 2) Module
- [x] AIR-Pro Series: Pediatrics (2016)
- [x] AIR-Pro Series: Trauma (2015)
- [x] AIR-Pro: Toxicology (Part 1)
- [x] ALiEM Book Club Page
- [x] ALiEM Book Club: Beyond the ED - Recommendations by Dr. Ed Newton
- [x] ALiEM Book Club: Beyond the ED - Recommendations from Dr. Jamie Santistevan
- [x] ALiEM Bookclub: Beyond the ED – Recommendations by Dr. Lainie Yarris
- [x] ALiEM Bookclub: Beyond the ED – Recommendations by Dr. Louis Ling
- [x] ALiEM Bookclub: Beyond the ED – Recommendations by Dr. Mike Gisondi
- [x] ALiEM Faculty Incubator
- [x] ALiEMU CAPSULES Module 4: Pharmacology of Emergency Airway Management – Part 2
- [x] ALiEMU CAPSULES Module 5: Procedural Sedation & Analgesia in the ED
- [x] ALiEMU CAPSULES Module 6: Pharmacology of Acute Coronary Syndromes
- [x] ALiEMU CAPSULES Module 7: Emergency Thyroid Disorders
- [x] ALiEMU School Doors Open - Featuring the CAPSULES Series
- [x] Approved Instructional Resources (AIR Series)
- [x] Approved Instructional Resources - Professional (AIR Pro Series)
- [x] Blood Cultures in Pneumonia
- [x] I am Amal Mattu, ECG nerd and author of Emergency ECG Video of the Week: How I Work Smarter
- [x] I am Damian Roland - Pediatric Emergency Physician & Blogger at Rolobot Rambles: How I Work Smarter
- [x] I am Dan Egan, EM Residency Program Director at St. Luke's-Roosevelt: How I Stay Healthy in EM
- [x] I am Dr. Alicia Pilarski - How I Promote Wellness in EM
- [x] I am Dr. Ambrose Wong, Director of Simulation Research: How I Stay Healthy in EM
- [x] I am Dr. Anand Swaminathan - Co-Creator for EM Lyceum & Omnipresent Educator: How I Work Smarter
- [x] I am Dr. Anand Swaminathan, Editor-in-Chief of Core EM: How I Stay Healthy in EM
- [x] I am Dr. Antony Robert, Emergency Medicine Resident: How I Stay Healthy in EM
- [x] I am Dr. Bory Kea, Assistant Professor and EM Physician: How I Stay Healthy in EM
- [x] I am Dr. Brian Lin, Emergency Physician, Blogger, and Educator: How I Stay Healthy in EM
- [x] I am Dr. Brian Rowe, Scientific Director and Research Guru: How I Stay Healthy in EM
- [x] I am Dr. Carl Alsup, Ultrasound Fellow: How I Stay Healthy in EM
- [x] I am Dr. Carolyn Snider, Chief Investigator of the EDVIP Program: How I Stay Healthy in EM
- [x] I am Dr. Catherine Varner, Emergency Physician and Clinical Scientist: How I Stay Healthy in EM
- [x] I am Dr. Chau Pham, Coordinator of the High Performance Physician Program: How I Stay Healthy in EM
- [x] I am Dr. Demian Szyld, Medical Director of NYSIM: How I Stay Healthy in EM
- [x] I am Dr. Erica Dance, Assistant Dean of Resident & Fellow Affairs at University of Alberta: How I Stay Healthy in EM
- [x] I am Dr. Graham Walker, Co-Creator of MDCalc: How I Stay Healthy in EM
- [x] I am Dr. Greg Wanner, Emergency Medicine Resident: How I Stay Healthy in EM
- [x] I am Dr. Ian Julie, Medical Simulation Fellowship Director: How I Stay Healthy in EM
- [x] I am Dr. James Huffman, STARS Airway Course Director, Transport Physician, and Clinical Educator: How I Stay Healthy in EM
- [x] I am Dr. Kathryn Dong, Director of ARCH and Inner City Health and Wellness: How I Stay Healthy in EM
- [x] I am Dr. Ken Milne, Creator of Skeptics’ Guide to Emergency Medicine: How I Work Smarter
- [x] I am Dr. Mahmood Hasan, Emergency Medicine Resident: How I Stay Healthy in EM
- [x] I am Dr. Martin Huecker, Associate PD and Research Director: How I Stay Healthy in EM
- [x] I am Dr. Masashi Rotte, Emergency Physician and Assistant Professor: How I Stay Healthy in EM
- [x] I am Dr. Matt Dawson - Co-Host of Ultrasound Podcast: How I Work Smarter
- [x] I am Dr. Matt Fields, Ultrasound Fellowship Director: How I Stay Healthy in EM
- [x] I am Dr. Megan Fix, Associate Program Director: How I Stay Healthy in EM
- [x] I am Dr. Melody Ong, Emergency Medicine Resident: How I Stay Healthy in EM
- [x] I am Dr. Michelle Lall - How I Promote Wellness in EM
- [x] I am Dr. Nadim Lalani, Assistant Program Director and Life Coach: How I Stay Healthy in EM
- [x] I am Dr. Philippe Ouellet, Emergency Medicine Resident: How I Stay Healthy in EM
- [x] I am Dr. Richard Bounds, Associate Program Director: How I Stay Healthy in EM
- [x] I am Dr. Rob Mac Sweeney, Editor for Critical Care Reviews: How I Work Smarter
- [x] I am Dr. Rob Woods, Program Director, Medical Advisor, and STARS Transport Physician: How I Stay Healthy in EM
- [x] I am Dr. Ryan Tam, Emergency Medicine Resident: How I Stay Healthy in EM
- [x] I am Dr. Sam Ko, Associate Medical Director: How I Stay Healthy in EM
- [x] I am Dr. Sara Gray, Medical Director of Emergency Preparedness: How I Stay Healthy in EM
- [x] I am Dr. Zafrina Poonja: How I Stay Healthy In EM
- [x] I am Esther Choo - Researcher, Public Health Advocate, and Educator: How I Work Smarter
- [x] I am Lainie Yarris, Residency Director at OHSU: How I Work Smarter
- [x] I am Michelle Lin, ALiEM Editor in Chief: How I Work Smarter
- [x] I am Natalie May - Emergency physician and blogger at St Emlyn's: How I Work Smarter
- [x] I am Salim Rezaie, Editor in Chief of REBEL-EM: How I Work Smarter
- [x] I am Victoria Brazil, Academic Lead for Clinical Skills and Simulation at Bond University: How I Work Smarter
- [x] Introducing the New ALiEMU Capsules Series
- [x] MEdIC Series | The Case of the Catastrophic Classroom - #CORDaa16 Edition
- [x] New Advanced "AIR Professional" Series: AIR-Pro
- [x] New AIR Series: ALiEM Approved Instructional Resources
- [x] New initiative: Wellness Think Tank for EM residents
- [x] New Series: How I Work Smarter
- [x] Paucis Verbis: Overanticoagulation and supratherapeutic INR
- [x] Sneak peek at ALiEMU: Free on-demand MOOC-like courses featuring the AIR Series
- [x] Top 5 Reasons to Join the ALiEM Fellowship Incubator: The "Fincubator"
- [x] Ultrasound For The Win Case – 46F with Abdominal Pain #US4TW
- [x] Ultrasound For the Win! Case - 55-year-old man with chest pain #US4TW
- [x] Ultrasound For The Win! Case – 101M with Altered Mental Status #US4TW
- [x] Ultrasound For The Win! Case – 40F with Fever, Chest Pain, Shortness of Breath
- [x] Ultrasound For the Win! Case – 43-year-old Man with Syncope #US4TW
- [x] Ultrasound For The Win! Case – 76M with Right-Sided Vision Loss #US4TW
- [x] Ultrasound For The Win! Case – 93F with Chest Pain
- [x] Ultrasound For the Win! Case: 38-year-old pregnant woman with acute right-sided abdominal pain #US4TW
- [x] Ultrasound For The Win! – 63M with an Erythematous Abdomen #US4TW
- [x] Ultrasound For The Win: 46F with Right Abdominal and Flank Pain #US4TW
- [x] Uncomplicated Urinary Tract Infections in Older Adults: Diagnosis and Treatment (Part 2)
- [x] US4TW Case: 28F with Shortness of Breath
- [x] US4TW Case: 30M with Blunt Abdominal Trauma
- [x] US4TW Case: 39F with Chest Pain
- [x] US4TW Case: 74F with Right Arm Tingling | Ultrasound for the Win series
- [x] We are the Residents and Faculty at Saint Louis University and Washington University: How We Stay Healthy in EM
- [x] Wellness and Resiliency During Residency: Interprofessional Conflict
- [x] Wellness and Resiliency During Residency: Strategizing with ZDoggMD
- [x] Wellness Think Tank: Improving Physician Wellness and Resiliency from the Ground Up

**Comment by dsifford** [comment]
## Remove / Replace the following
- [x] [BEEM score table](https://www.aliem.com/wp-admin/post.php?post=34191&action=edit)
- [x] [Case of Cognitive Overload MEdIC](https://www.aliem.com/wp-admin/post.php?post=34420&action=edit)
- [x] [available-badge-amazon](https://www.aliem.com/wp-admin/post.php?post=33752&action=edit)
- [x] [get it on ibooks button](https://www.aliem.com/wp-admin/post.php?post=33752&action=edit)
- [x] [Dropbox icon](https://www.aliem.com/wp-admin/post.php?post=35&action=edit)
- [x] [Evernote icon](https://www.aliem.com/wp-admin/post.php?post=35&action=edit)
- [x] [iBooks icon text](https://www.aliem.com/wp-admin/post.php?post=31925&action=edit) (2 others also)
- [x] [Grading Treatment Scorpion envenomation](https://www.aliem.com/wp-admin/post.php?post=31829&action=edit)
- [x] [Case of Fibbing First Year MEdiC](https://www.aliem.com/wp-admin/post.php?post=31067&action=edit)
- [x] [Alvarado score pediatric appendicitis](https://www.aliem.com/wp-admin/post.php?post=30819&action=edit)
- [x] [Appy Score strata pediatric appendicitis](https://www.aliem.com/wp-admin/post.php?post=30819&action=edit)
- [x] [Vascular Access Techniques](https://www.aliem.com/wp-admin/post.php?post=30572&action=edit)
- [x] [Case 3.06 MEdIC](https://www.aliem.com/wp-admin/post.php?post=30570&action=edit)
- [x] [Chief Resident Incubator and Dynamed Plus logo](https://www.aliem.com/wp-admin/post.php?post=30167&action=edit)
- [x] [MEdiC 3.05 Small](https://www.aliem.com/wp-admin/post.php?post=30073&action=edit)
- [x] [Case 3.04 - Awkward Assessors MEdIC](https://www.aliem.com/wp-admin/post.php?post=29271&action=edit)
- [x] [Hippo Education Essentials of Emergency Medicine EEM logo](https://www.aliem.com/wp-admin/post.php?post=28440&action=edit)
- [x] [Essentials of Emergency Medicine icon EEM](https://www.aliem.com/wp-admin/post.php?post=28440&action=edit)
- [x] [Faculty Incubator logo with tagline](https://www.aliem.com/wp-admin/post.php?post=28041&action=edit)
- [x] [Fellowship Incubator with tagline](https://www.aliem.com/wp-admin/post.php?post=27679&action=edit)
- [x] [Chief Resident incubator logo](https://www.aliem.com/wp-admin/post.php?post=22302&action=edit)
- [x] [MEdIC Mini 3.03 Case of Cackling Resident](https://www.aliem.com/wp-admin/post.php?post=28000&action=edit)
- [x] [MeDIC 3.02 No Learner Policy PDF](https://www.aliem.com/wp-admin/post.php?post=27703&action=edit)
- [x] [2.09 Mini MEdIC Commentary pdf](https://www.aliem.com/wp-admin/post.php?post=24471&action=edit)
- [x] [MEdIC Series - Case 2.08](https://www.aliem.com/wp-admin/post.php?post=23750&action=edit)
- [x] [2.07 Mini medic](https://www.aliem.com/wp-admin/post.php?post=23203&action=edit)
- [x] [2.06 medic mini](https://www.aliem.com/wp-admin/post.php?post=22831&action=edit)
- [x] [MEdIC Mini 2.05](https://www.aliem.com/wp-admin/post.php?post=22123&action=edit)
- [x] [2.01 mini MEdIC](https://www.aliem.com/wp-admin/post.php?post=19416&action=edit)
- [x] https://www.aliem.com/wp-content/uploads/APE-table.png
- [x] [1.11 mini MEdICs Copy](https://www.aliem.com/wp-admin/post.php?post=16989&action=edit)
- [x] [1.08 mini Medics copy](https://www.aliem.com/wp-content/uploads/1.08-mini-Medics-copy1.jpg)
- [x] [1.08 mini Medics copy](https://www.aliem.com/wp-admin/post.php?post=10624&action=edit)
- [x] [1.07 mini Medics copy](https://www.aliem.com/wp-content/uploads/1.07-mini-Medics-copy.jpg)
- [x] [1.06 mini Medics copy](https://www.aliem.com/wp-admin/post.php?post=10624&action=edit)
- [x] [1.05 mini Medics copy](https://www.aliem.com/wp-content/uploads/1.05-mini-Medics-copy.jpg)
- [x] [1.04 mini Medics copy](https://www.aliem.com/wp-content/uploads/1.04-mini-Medics-copy.jpg)
- [x] [1.03 mini Medics copy](https://www.aliem.com/wp-content/uploads/1.03-mini-Medics-copy.jpg)
- [x] [1.02 Mini Medics copy](https://www.aliem.com/wp-content/uploads/1.02-Mini-Medics-copy.jpg)
- [x] [Case of the Woman in White MEdIC](https://www.aliem.com/wp-content/uploads/2013/08/Case-of-the-Woman-in-White.png)
- [x] [ABEM milestones on team management](https://www.aliem.com/wp-admin/post.php?post=8746&action=edit)
- [x] [ABEM milestone on multi-tasking task-switching](https://www.aliem.com/wp-admin/post.php?post=8746&action=edit)
- [x] [TableMacrocognition](https://www.aliem.com/wp-admin/post.php?post=262&action=edit)
